# Generated by Django 4.0.3 on 2022-04-01 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(upload_to='blog/images')),
                ('fecha', models.DateField(verbose_name=datetime.datetime.today)),
            ],
        ),
    ]
